# Generated by Django 3.1.1 on 2022-06-13 05:01

from django.db import migrations, models
import personas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(blank=True, max_length=30, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(null=True, upload_to=personas.models.cargarFotoProducto)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('apellido', models.ImageField(blank=True, max_length=50, null=True, upload_to='', verbose_name='Apellido')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
