# Generated by Django 3.1.1 on 2022-06-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20220613_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Correo'),
        ),
    ]
